language: ruby
rvm: 2.4.1
script: bundle exec rake spec

services:
  - postgresql

before_script:
  - psql -c 'create database ft_ratings;' -U postgres
  - psql -c 'create database ft_ratings_test;' -U postgres
